//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.261
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zkdao.Web.OrderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCartDataObject", Namespace="http://www.zkdao.com/ShoppingCartDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class ShoppingCartDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.OrderServiceReference.ShoppingCartItemDataObjectList ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SubtotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public zkdao.Web.OrderServiceReference.ShoppingCartItemDataObjectList Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<decimal> Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ShoppingCartItemDataObjectList", Namespace="http://www.zkdao.com/CollectionDataObjectList.xsd", ItemName="ShoppingCartItemDataObject")]
    [System.SerializableAttribute()]
    public class ShoppingCartItemDataObjectList : System.Collections.Generic.List<zkdao.Web.OrderServiceReference.ShoppingCartItemDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCartItemDataObject", Namespace="http://www.zkdao.com/ShoppingCartItemDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class ShoppingCartItemDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.OrderServiceReference.LaptopDataObject LaptopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LineAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShoppingCartIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public zkdao.Web.OrderServiceReference.LaptopDataObject Laptop {
            get {
                return this.LaptopField;
            }
            set {
                if ((object.ReferenceEquals(this.LaptopField, value) != true)) {
                    this.LaptopField = value;
                    this.RaisePropertyChanged("Laptop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<decimal> LineAmount {
            get {
                return this.LineAmountField;
            }
            set {
                if ((this.LineAmountField.Equals(value) != true)) {
                    this.LineAmountField = value;
                    this.RaisePropertyChanged("LineAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ShoppingCartID {
            get {
                return this.ShoppingCartIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartIDField, value) != true)) {
                    this.ShoppingCartIDField = value;
                    this.RaisePropertyChanged("ShoppingCartID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LaptopDataObject", Namespace="http://www.zkdao.com/LaptopDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class LaptopDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.OrderServiceReference.LaptopConfigurationDataObject ConfigurationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public zkdao.Web.OrderServiceReference.LaptopConfigurationDataObject Configuration {
            get {
                return this.ConfigurationField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigurationField, value) != true)) {
                    this.ConfigurationField = value;
                    this.RaisePropertyChanged("Configuration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LaptopConfigurationDataObject", Namespace="http://www.zkdao.com/LaptopConfigurationDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class LaptopConfigurationDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HardDiskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoAdapterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPU {
            get {
                return this.CPUField;
            }
            set {
                if ((object.ReferenceEquals(this.CPUField, value) != true)) {
                    this.CPUField = value;
                    this.RaisePropertyChanged("CPU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memory {
            get {
                return this.MemoryField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoryField, value) != true)) {
                    this.MemoryField = value;
                    this.RaisePropertyChanged("Memory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Board {
            get {
                return this.BoardField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardField, value) != true)) {
                    this.BoardField = value;
                    this.RaisePropertyChanged("Board");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string HardDisk {
            get {
                return this.HardDiskField;
            }
            set {
                if ((object.ReferenceEquals(this.HardDiskField, value) != true)) {
                    this.HardDiskField = value;
                    this.RaisePropertyChanged("HardDisk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string VideoAdapter {
            get {
                return this.VideoAdapterField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoAdapterField, value) != true)) {
                    this.VideoAdapterField = value;
                    this.RaisePropertyChanged("VideoAdapter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderDataObject", Namespace="http://www.zkdao.com/SalesOrderDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class SalesOrderDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDispatchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeliveredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.OrderServiceReference.SalesLineDataObjectList SalesLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SubtotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> DateDispatched {
            get {
                return this.DateDispatchedField;
            }
            set {
                if ((this.DateDispatchedField.Equals(value) != true)) {
                    this.DateDispatchedField = value;
                    this.RaisePropertyChanged("DateDispatched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> DateDelivered {
            get {
                return this.DateDeliveredField;
            }
            set {
                if ((this.DateDeliveredField.Equals(value) != true)) {
                    this.DateDeliveredField = value;
                    this.RaisePropertyChanged("DateDelivered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string CustomerContact {
            get {
                return this.CustomerContactField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerContactField, value) != true)) {
                    this.CustomerContactField = value;
                    this.RaisePropertyChanged("CustomerContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string CustomerAddressCountry {
            get {
                return this.CustomerAddressCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressCountryField, value) != true)) {
                    this.CustomerAddressCountryField = value;
                    this.RaisePropertyChanged("CustomerAddressCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CustomerAddressState {
            get {
                return this.CustomerAddressStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressStateField, value) != true)) {
                    this.CustomerAddressStateField = value;
                    this.RaisePropertyChanged("CustomerAddressState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string CustomerAddressCity {
            get {
                return this.CustomerAddressCityField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressCityField, value) != true)) {
                    this.CustomerAddressCityField = value;
                    this.RaisePropertyChanged("CustomerAddressCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string CustomerAddressStreet {
            get {
                return this.CustomerAddressStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressStreetField, value) != true)) {
                    this.CustomerAddressStreetField = value;
                    this.RaisePropertyChanged("CustomerAddressStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string CustomerAddressZip {
            get {
                return this.CustomerAddressZipField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressZipField, value) != true)) {
                    this.CustomerAddressZipField = value;
                    this.RaisePropertyChanged("CustomerAddressZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public zkdao.Web.OrderServiceReference.SalesLineDataObjectList SalesLines {
            get {
                return this.SalesLinesField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesLinesField, value) != true)) {
                    this.SalesLinesField = value;
                    this.RaisePropertyChanged("SalesLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<decimal> Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SalesLineDataObjectList", Namespace="http://www.zkdao.com/CollectionDataObjectList.xsd", ItemName="SalesLineDataObject")]
    [System.SerializableAttribute()]
    public class SalesLineDataObjectList : System.Collections.Generic.List<zkdao.Web.OrderServiceReference.SalesLineDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesLineDataObject", Namespace="http://www.zkdao.com/SalesLineDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class SalesLineDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesOrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.OrderServiceReference.LaptopDataObject LaptopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LineAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SalesOrderID {
            get {
                return this.SalesOrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesOrderIDField, value) != true)) {
                    this.SalesOrderIDField = value;
                    this.RaisePropertyChanged("SalesOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public zkdao.Web.OrderServiceReference.LaptopDataObject Laptop {
            get {
                return this.LaptopField;
            }
            set {
                if ((object.ReferenceEquals(this.LaptopField, value) != true)) {
                    this.LaptopField = value;
                    this.RaisePropertyChanged("Laptop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<decimal> LineAmount {
            get {
                return this.LineAmountField;
            }
            set {
                if ((this.LineAmountField.Equals(value) != true)) {
                    this.LineAmountField = value;
                    this.RaisePropertyChanged("LineAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.zkdao.com", ConfigurationName="OrderServiceReference.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IOrderService/AddProductToCart", ReplyAction="http://www.zkdao.com/IOrderService/AddProductToCartResponse")]
        void AddProductToCart(System.Guid customerID, System.Guid productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IOrderService/GetShoppingCart", ReplyAction="http://www.zkdao.com/IOrderService/GetShoppingCartResponse")]
        zkdao.Web.OrderServiceReference.ShoppingCartDataObject GetShoppingCart(System.Guid customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IOrderService/UpdateShoppingCartItem", ReplyAction="http://www.zkdao.com/IOrderService/UpdateShoppingCartItemResponse")]
        void UpdateShoppingCartItem(System.Guid shoppingCartItemID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IOrderService/DeleteShoppingCartItem", ReplyAction="http://www.zkdao.com/IOrderService/DeleteShoppingCartItemResponse")]
        void DeleteShoppingCartItem(System.Guid shoppingCartItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IOrderService/Checkout", ReplyAction="http://www.zkdao.com/IOrderService/CheckoutResponse")]
        void Checkout(System.Guid customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IOrderService/Confirm", ReplyAction="http://www.zkdao.com/IOrderService/ConfirmResponse")]
        void Confirm(System.Guid orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IOrderService/GetSalesOrder", ReplyAction="http://www.zkdao.com/IOrderService/GetSalesOrderResponse")]
        zkdao.Web.OrderServiceReference.SalesOrderDataObject GetSalesOrder(System.Guid orderID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : zkdao.Web.OrderServiceReference.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<zkdao.Web.OrderServiceReference.IOrderService>, zkdao.Web.OrderServiceReference.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddProductToCart(System.Guid customerID, System.Guid productID) {
            base.Channel.AddProductToCart(customerID, productID);
        }
        
        public zkdao.Web.OrderServiceReference.ShoppingCartDataObject GetShoppingCart(System.Guid customerID) {
            return base.Channel.GetShoppingCart(customerID);
        }
        
        public void UpdateShoppingCartItem(System.Guid shoppingCartItemID, int quantity) {
            base.Channel.UpdateShoppingCartItem(shoppingCartItemID, quantity);
        }
        
        public void DeleteShoppingCartItem(System.Guid shoppingCartItemID) {
            base.Channel.DeleteShoppingCartItem(shoppingCartItemID);
        }
        
        public void Checkout(System.Guid customerID) {
            base.Channel.Checkout(customerID);
        }
        
        public void Confirm(System.Guid orderID) {
            base.Channel.Confirm(orderID);
        }
        
        public zkdao.Web.OrderServiceReference.SalesOrderDataObject GetSalesOrder(System.Guid orderID) {
            return base.Channel.GetSalesOrder(orderID);
        }
    }
}
