//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.261
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zkdao.Web.ProductServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LaptopDataObjectList", Namespace="http://www.zkdao.com/CollectionDataObjectList.xsd", ItemName="LaptopDataObject")]
    [System.SerializableAttribute()]
    public class LaptopDataObjectList : System.Collections.Generic.List<zkdao.Web.ProductServiceReference.LaptopDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LaptopDataObject", Namespace="http://www.zkdao.com/LaptopDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class LaptopDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.ProductServiceReference.LaptopConfigurationDataObject ConfigurationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public zkdao.Web.ProductServiceReference.LaptopConfigurationDataObject Configuration {
            get {
                return this.ConfigurationField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigurationField, value) != true)) {
                    this.ConfigurationField = value;
                    this.RaisePropertyChanged("Configuration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LaptopConfigurationDataObject", Namespace="http://www.zkdao.com/LaptopConfigurationDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class LaptopConfigurationDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HardDiskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoAdapterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPU {
            get {
                return this.CPUField;
            }
            set {
                if ((object.ReferenceEquals(this.CPUField, value) != true)) {
                    this.CPUField = value;
                    this.RaisePropertyChanged("CPU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memory {
            get {
                return this.MemoryField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoryField, value) != true)) {
                    this.MemoryField = value;
                    this.RaisePropertyChanged("Memory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Board {
            get {
                return this.BoardField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardField, value) != true)) {
                    this.BoardField = value;
                    this.RaisePropertyChanged("Board");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string HardDisk {
            get {
                return this.HardDiskField;
            }
            set {
                if ((object.ReferenceEquals(this.HardDiskField, value) != true)) {
                    this.HardDiskField = value;
                    this.RaisePropertyChanged("HardDisk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string VideoAdapter {
            get {
                return this.VideoAdapterField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoAdapterField, value) != true)) {
                    this.VideoAdapterField = value;
                    this.RaisePropertyChanged("VideoAdapter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.zkdao.com", ConfigurationName="ProductServiceReference.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IProductService/GetLaptops", ReplyAction="http://www.zkdao.com/IProductService/GetLaptopsResponse")]
        zkdao.Web.ProductServiceReference.LaptopDataObjectList GetLaptops();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IProductService/GetLaptop", ReplyAction="http://www.zkdao.com/IProductService/GetLaptopResponse")]
        zkdao.Web.ProductServiceReference.LaptopDataObject GetLaptop(System.Guid ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IProductService/CreateLaptop", ReplyAction="http://www.zkdao.com/IProductService/CreateLaptopResponse")]
        System.Guid CreateLaptop(zkdao.Web.ProductServiceReference.LaptopDataObject laptopDataObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IProductService/CreateLaptops", ReplyAction="http://www.zkdao.com/IProductService/CreateLaptopsResponse")]
        void CreateLaptops(zkdao.Web.ProductServiceReference.LaptopDataObjectList laptopDataObjects);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : zkdao.Web.ProductServiceReference.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<zkdao.Web.ProductServiceReference.IProductService>, zkdao.Web.ProductServiceReference.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public zkdao.Web.ProductServiceReference.LaptopDataObjectList GetLaptops() {
            return base.Channel.GetLaptops();
        }
        
        public zkdao.Web.ProductServiceReference.LaptopDataObject GetLaptop(System.Guid ID) {
            return base.Channel.GetLaptop(ID);
        }
        
        public System.Guid CreateLaptop(zkdao.Web.ProductServiceReference.LaptopDataObject laptopDataObject) {
            return base.Channel.CreateLaptop(laptopDataObject);
        }
        
        public void CreateLaptops(zkdao.Web.ProductServiceReference.LaptopDataObjectList laptopDataObjects) {
            base.Channel.CreateLaptops(laptopDataObjects);
        }
    }
}
