//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zkdao.Web.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/zkdao.Domain")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateLastLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateLastPasswordChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.InfoReplyData[] PostInfoReplysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.InfoData[] PostInfosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.ProductReplyData[] PostProductReplysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.ReplyChildData[] PostReplyChildsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.UserRelaInfoData[] UserRelaInfosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.UserRelaProductData[] UserRelaProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.UserRelaReplyData[] UserRelaReplysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeiboField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActEnum {
            get {
                return this.ActEnumField;
            }
            set {
                if ((this.ActEnumField.Equals(value) != true)) {
                    this.ActEnumField = value;
                    this.RaisePropertyChanged("ActEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateLastLogin {
            get {
                return this.DateLastLoginField;
            }
            set {
                if ((this.DateLastLoginField.Equals(value) != true)) {
                    this.DateLastLoginField = value;
                    this.RaisePropertyChanged("DateLastLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateLastPasswordChange {
            get {
                return this.DateLastPasswordChangeField;
            }
            set {
                if ((this.DateLastPasswordChangeField.Equals(value) != true)) {
                    this.DateLastPasswordChangeField = value;
                    this.RaisePropertyChanged("DateLastPasswordChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.InfoReplyData[] PostInfoReplys {
            get {
                return this.PostInfoReplysField;
            }
            set {
                if ((object.ReferenceEquals(this.PostInfoReplysField, value) != true)) {
                    this.PostInfoReplysField = value;
                    this.RaisePropertyChanged("PostInfoReplys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.InfoData[] PostInfos {
            get {
                return this.PostInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.PostInfosField, value) != true)) {
                    this.PostInfosField = value;
                    this.RaisePropertyChanged("PostInfos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.ProductReplyData[] PostProductReplys {
            get {
                return this.PostProductReplysField;
            }
            set {
                if ((object.ReferenceEquals(this.PostProductReplysField, value) != true)) {
                    this.PostProductReplysField = value;
                    this.RaisePropertyChanged("PostProductReplys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.ReplyChildData[] PostReplyChilds {
            get {
                return this.PostReplyChildsField;
            }
            set {
                if ((object.ReferenceEquals(this.PostReplyChildsField, value) != true)) {
                    this.PostReplyChildsField = value;
                    this.RaisePropertyChanged("PostReplyChilds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QQ {
            get {
                return this.QQField;
            }
            set {
                if ((object.ReferenceEquals(this.QQField, value) != true)) {
                    this.QQField = value;
                    this.RaisePropertyChanged("QQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleEnum {
            get {
                return this.RoleEnumField;
            }
            set {
                if ((this.RoleEnumField.Equals(value) != true)) {
                    this.RoleEnumField = value;
                    this.RaisePropertyChanged("RoleEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.UserRelaInfoData[] UserRelaInfos {
            get {
                return this.UserRelaInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRelaInfosField, value) != true)) {
                    this.UserRelaInfosField = value;
                    this.RaisePropertyChanged("UserRelaInfos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.UserRelaProductData[] UserRelaProducts {
            get {
                return this.UserRelaProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRelaProductsField, value) != true)) {
                    this.UserRelaProductsField = value;
                    this.RaisePropertyChanged("UserRelaProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.UserRelaReplyData[] UserRelaReplys {
            get {
                return this.UserRelaReplysField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRelaReplysField, value) != true)) {
                    this.UserRelaReplysField = value;
                    this.RaisePropertyChanged("UserRelaReplys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weibo {
            get {
                return this.WeiboField;
            }
            set {
                if ((object.ReferenceEquals(this.WeiboField, value) != true)) {
                    this.WeiboField = value;
                    this.RaisePropertyChanged("Weibo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoReplyData", Namespace="http://schemas.datacontract.org/2004/07/zkdao.Domain")]
    [System.SerializableAttribute()]
    public partial class InfoReplyData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentRichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.InfoData InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinusAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlusAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.UserData PosterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActEnum {
            get {
                return this.ActEnumField;
            }
            set {
                if ((this.ActEnumField.Equals(value) != true)) {
                    this.ActEnumField = value;
                    this.RaisePropertyChanged("ActEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentRich {
            get {
                return this.ContentRichField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentRichField, value) != true)) {
                    this.ContentRichField = value;
                    this.RaisePropertyChanged("ContentRich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatTime {
            get {
                return this.CreatTimeField;
            }
            set {
                if ((this.CreatTimeField.Equals(value) != true)) {
                    this.CreatTimeField = value;
                    this.RaisePropertyChanged("CreatTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.InfoData Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinusAmount {
            get {
                return this.MinusAmountField;
            }
            set {
                if ((this.MinusAmountField.Equals(value) != true)) {
                    this.MinusAmountField = value;
                    this.RaisePropertyChanged("MinusAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlusAmount {
            get {
                return this.PlusAmountField;
            }
            set {
                if ((this.PlusAmountField.Equals(value) != true)) {
                    this.PlusAmountField = value;
                    this.RaisePropertyChanged("PlusAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.UserData Poster {
            get {
                return this.PosterField;
            }
            set {
                if ((object.ReferenceEquals(this.PosterField, value) != true)) {
                    this.PosterField = value;
                    this.RaisePropertyChanged("Poster");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoData", Namespace="http://schemas.datacontract.org/2004/07/zkdao.Domain")]
    [System.SerializableAttribute()]
    public partial class InfoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentRichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradeAverageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.UserData PosterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.ProductData ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.InfoReplyData[] ReplysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.InfoRelaTagData[] TagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActEnum {
            get {
                return this.ActEnumField;
            }
            set {
                if ((this.ActEnumField.Equals(value) != true)) {
                    this.ActEnumField = value;
                    this.RaisePropertyChanged("ActEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentRich {
            get {
                return this.ContentRichField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentRichField, value) != true)) {
                    this.ContentRichField = value;
                    this.RaisePropertyChanged("ContentRich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GradeAverage {
            get {
                return this.GradeAverageField;
            }
            set {
                if ((this.GradeAverageField.Equals(value) != true)) {
                    this.GradeAverageField = value;
                    this.RaisePropertyChanged("GradeAverage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkImage {
            get {
                return this.LinkImageField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkImageField, value) != true)) {
                    this.LinkImageField = value;
                    this.RaisePropertyChanged("LinkImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkUrl {
            get {
                return this.LinkUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkUrlField, value) != true)) {
                    this.LinkUrlField = value;
                    this.RaisePropertyChanged("LinkUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.UserData Poster {
            get {
                return this.PosterField;
            }
            set {
                if ((object.ReferenceEquals(this.PosterField, value) != true)) {
                    this.PosterField = value;
                    this.RaisePropertyChanged("Poster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.ProductData Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.InfoReplyData[] Replys {
            get {
                return this.ReplysField;
            }
            set {
                if ((object.ReferenceEquals(this.ReplysField, value) != true)) {
                    this.ReplysField = value;
                    this.RaisePropertyChanged("Replys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.InfoRelaTagData[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductReplyData", Namespace="http://schemas.datacontract.org/2004/07/zkdao.Domain")]
    [System.SerializableAttribute()]
    public partial class ProductReplyData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdvContentRicjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinusAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlusAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.UserData PosterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.ProductData ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortContentRichField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActEnum {
            get {
                return this.ActEnumField;
            }
            set {
                if ((this.ActEnumField.Equals(value) != true)) {
                    this.ActEnumField = value;
                    this.RaisePropertyChanged("ActEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdvContentRicj {
            get {
                return this.AdvContentRicjField;
            }
            set {
                if ((object.ReferenceEquals(this.AdvContentRicjField, value) != true)) {
                    this.AdvContentRicjField = value;
                    this.RaisePropertyChanged("AdvContentRicj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatTime {
            get {
                return this.CreatTimeField;
            }
            set {
                if ((this.CreatTimeField.Equals(value) != true)) {
                    this.CreatTimeField = value;
                    this.RaisePropertyChanged("CreatTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinusAmount {
            get {
                return this.MinusAmountField;
            }
            set {
                if ((this.MinusAmountField.Equals(value) != true)) {
                    this.MinusAmountField = value;
                    this.RaisePropertyChanged("MinusAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlusAmount {
            get {
                return this.PlusAmountField;
            }
            set {
                if ((this.PlusAmountField.Equals(value) != true)) {
                    this.PlusAmountField = value;
                    this.RaisePropertyChanged("PlusAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.UserData Poster {
            get {
                return this.PosterField;
            }
            set {
                if ((object.ReferenceEquals(this.PosterField, value) != true)) {
                    this.PosterField = value;
                    this.RaisePropertyChanged("Poster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.ProductData Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortContentRich {
            get {
                return this.ShortContentRichField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortContentRichField, value) != true)) {
                    this.ShortContentRichField = value;
                    this.RaisePropertyChanged("ShortContentRich");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReplyChildData", Namespace="http://schemas.datacontract.org/2004/07/zkdao.Domain")]
    [System.SerializableAttribute()]
    public partial class ReplyChildData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.UserData PosterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActEnum {
            get {
                return this.ActEnumField;
            }
            set {
                if ((this.ActEnumField.Equals(value) != true)) {
                    this.ActEnumField = value;
                    this.RaisePropertyChanged("ActEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatTime {
            get {
                return this.CreatTimeField;
            }
            set {
                if ((this.CreatTimeField.Equals(value) != true)) {
                    this.CreatTimeField = value;
                    this.RaisePropertyChanged("CreatTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.UserData Poster {
            get {
                return this.PosterField;
            }
            set {
                if ((object.ReferenceEquals(this.PosterField, value) != true)) {
                    this.PosterField = value;
                    this.RaisePropertyChanged("Poster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetID {
            get {
                return this.TargetIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetIDField, value) != true)) {
                    this.TargetIDField = value;
                    this.RaisePropertyChanged("TargetID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRelaInfoData", Namespace="http://schemas.datacontract.org/2004/07/zkdao.Domain")]
    [System.SerializableAttribute()]
    public partial class UserRelaInfoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiveGradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.UserData UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GiveGrade {
            get {
                return this.GiveGradeField;
            }
            set {
                if ((this.GiveGradeField.Equals(value) != true)) {
                    this.GiveGradeField = value;
                    this.RaisePropertyChanged("GiveGrade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InfoID {
            get {
                return this.InfoIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoIDField, value) != true)) {
                    this.InfoIDField = value;
                    this.RaisePropertyChanged("InfoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.UserData User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRelaProductData", Namespace="http://schemas.datacontract.org/2004/07/zkdao.Domain")]
    [System.SerializableAttribute()]
    public partial class UserRelaProductData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiveGradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.UserData UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserToGoodsEnumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GiveGrade {
            get {
                return this.GiveGradeField;
            }
            set {
                if ((this.GiveGradeField.Equals(value) != true)) {
                    this.GiveGradeField = value;
                    this.RaisePropertyChanged("GiveGrade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEager {
            get {
                return this.IsEagerField;
            }
            set {
                if ((this.IsEagerField.Equals(value) != true)) {
                    this.IsEagerField = value;
                    this.RaisePropertyChanged("IsEager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.UserData User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserToGoodsEnum {
            get {
                return this.UserToGoodsEnumField;
            }
            set {
                if ((this.UserToGoodsEnumField.Equals(value) != true)) {
                    this.UserToGoodsEnumField = value;
                    this.RaisePropertyChanged("UserToGoodsEnum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRelaReplyData", Namespace="http://schemas.datacontract.org/2004/07/zkdao.Domain")]
    [System.SerializableAttribute()]
    public partial class UserRelaReplyData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PlusOrMinusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.UserData UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PlusOrMinus {
            get {
                return this.PlusOrMinusField;
            }
            set {
                if ((this.PlusOrMinusField.Equals(value) != true)) {
                    this.PlusOrMinusField = value;
                    this.RaisePropertyChanged("PlusOrMinus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetID {
            get {
                return this.TargetIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetIDField, value) != true)) {
                    this.TargetIDField = value;
                    this.RaisePropertyChanged("TargetID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.UserData User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductData", Namespace="http://schemas.datacontract.org/2004/07/zkdao.Domain")]
    [System.SerializableAttribute()]
    public partial class ProductData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EagerAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EagerHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradeAverageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceHistoryLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private zkdao.Web.UserServiceReference.ProductReplyData[] ReplysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActEnum {
            get {
                return this.ActEnumField;
            }
            set {
                if ((this.ActEnumField.Equals(value) != true)) {
                    this.ActEnumField = value;
                    this.RaisePropertyChanged("ActEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EagerAmount {
            get {
                return this.EagerAmountField;
            }
            set {
                if ((this.EagerAmountField.Equals(value) != true)) {
                    this.EagerAmountField = value;
                    this.RaisePropertyChanged("EagerAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EagerHistory {
            get {
                return this.EagerHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.EagerHistoryField, value) != true)) {
                    this.EagerHistoryField = value;
                    this.RaisePropertyChanged("EagerHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GradeAverage {
            get {
                return this.GradeAverageField;
            }
            set {
                if ((this.GradeAverageField.Equals(value) != true)) {
                    this.GradeAverageField = value;
                    this.RaisePropertyChanged("GradeAverage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeHistory {
            get {
                return this.GradeHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeHistoryField, value) != true)) {
                    this.GradeHistoryField = value;
                    this.RaisePropertyChanged("GradeHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceHistoryLink {
            get {
                return this.PriceHistoryLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceHistoryLinkField, value) != true)) {
                    this.PriceHistoryLinkField = value;
                    this.RaisePropertyChanged("PriceHistoryLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zkdao.Web.UserServiceReference.ProductReplyData[] Replys {
            get {
                return this.ReplysField;
            }
            set {
                if ((object.ReferenceEquals(this.ReplysField, value) != true)) {
                    this.ReplysField = value;
                    this.RaisePropertyChanged("Replys");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoRelaTagData", Namespace="http://schemas.datacontract.org/2004/07/zkdao.Domain")]
    [System.SerializableAttribute()]
    public partial class InfoRelaTagData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InfoID {
            get {
                return this.InfoIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoIDField, value) != true)) {
                    this.InfoIDField = value;
                    this.RaisePropertyChanged("InfoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagID {
            get {
                return this.TagIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TagIDField, value) != true)) {
                    this.TagIDField = value;
                    this.RaisePropertyChanged("TagID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.zkdao.com", ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UserGetByID", ReplyAction="http://www.zkdao.com/IUserService/UserGetByIDResponse")]
        zkdao.Web.UserServiceReference.UserData UserGetByID(System.Guid ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UserGetByKey", ReplyAction="http://www.zkdao.com/IUserService/UserGetByKeyResponse")]
        zkdao.Web.UserServiceReference.UserData UserGetByKey(string userkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UserGetPager", ReplyAction="http://www.zkdao.com/IUserService/UserGetPagerResponse")]
        zic_dotnet.Pager<zkdao.Web.UserServiceReference.UserData> UserGetPager(int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UserCreat", ReplyAction="http://www.zkdao.com/IUserService/UserCreatResponse")]
        System.Guid UserCreat(zkdao.Web.UserServiceReference.UserData dataObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UserValidate", ReplyAction="http://www.zkdao.com/IUserService/UserValidateResponse")]
        bool UserValidate(string userkey, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UserUpdate", ReplyAction="http://www.zkdao.com/IUserService/UserUpdateResponse")]
        void UserUpdate(string userkey, zkdao.Web.UserServiceReference.UserData dataObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : zkdao.Web.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<zkdao.Web.UserServiceReference.IUserService>, zkdao.Web.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public zkdao.Web.UserServiceReference.UserData UserGetByID(System.Guid ID) {
            return base.Channel.UserGetByID(ID);
        }
        
        public zkdao.Web.UserServiceReference.UserData UserGetByKey(string userkey) {
            return base.Channel.UserGetByKey(userkey);
        }
        
        public zic_dotnet.Pager<zkdao.Web.UserServiceReference.UserData> UserGetPager(int pageIndex, int pageSize) {
            return base.Channel.UserGetPager(pageIndex, pageSize);
        }
        
        public System.Guid UserCreat(zkdao.Web.UserServiceReference.UserData dataObject) {
            return base.Channel.UserCreat(dataObject);
        }
        
        public bool UserValidate(string userkey, string password) {
            return base.Channel.UserValidate(userkey, password);
        }
        
        public void UserUpdate(string userkey, zkdao.Web.UserServiceReference.UserData dataObject) {
            base.Channel.UserUpdate(userkey, dataObject);
        }
    }
}
