//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zkdao.Web.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/zkdao.Domain")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateLastLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateLastPasswordChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeiboField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActEnum {
            get {
                return this.ActEnumField;
            }
            set {
                if ((this.ActEnumField.Equals(value) != true)) {
                    this.ActEnumField = value;
                    this.RaisePropertyChanged("ActEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateLastLogin {
            get {
                return this.DateLastLoginField;
            }
            set {
                if ((this.DateLastLoginField.Equals(value) != true)) {
                    this.DateLastLoginField = value;
                    this.RaisePropertyChanged("DateLastLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateLastPasswordChange {
            get {
                return this.DateLastPasswordChangeField;
            }
            set {
                if ((this.DateLastPasswordChangeField.Equals(value) != true)) {
                    this.DateLastPasswordChangeField = value;
                    this.RaisePropertyChanged("DateLastPasswordChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QQ {
            get {
                return this.QQField;
            }
            set {
                if ((object.ReferenceEquals(this.QQField, value) != true)) {
                    this.QQField = value;
                    this.RaisePropertyChanged("QQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleEnum {
            get {
                return this.RoleEnumField;
            }
            set {
                if ((this.RoleEnumField.Equals(value) != true)) {
                    this.RoleEnumField = value;
                    this.RaisePropertyChanged("RoleEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weibo {
            get {
                return this.WeiboField;
            }
            set {
                if ((object.ReferenceEquals(this.WeiboField, value) != true)) {
                    this.WeiboField = value;
                    this.RaisePropertyChanged("Weibo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.zkdao.com", ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UserGetByID", ReplyAction="http://www.zkdao.com/IUserService/UserGetByIDResponse")]
        zkdao.Web.UserServiceReference.UserData UserGetByID(System.Guid ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UserGetByEmail", ReplyAction="http://www.zkdao.com/IUserService/UserGetByEmailResponse")]
        zkdao.Web.UserServiceReference.UserData UserGetByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UserGetPager", ReplyAction="http://www.zkdao.com/IUserService/UserGetPagerResponse")]
        zic_dotnet.Pager<zkdao.Web.UserServiceReference.UserData> UserGetPager(int pageNumber, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UserCreat", ReplyAction="http://www.zkdao.com/IUserService/UserCreatResponse")]
        System.Guid UserCreat(zkdao.Web.UserServiceReference.UserData dataObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UserValidate", ReplyAction="http://www.zkdao.com/IUserService/UserValidateResponse")]
        bool UserValidate(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zkdao.com/IUserService/UpdateCustomer", ReplyAction="http://www.zkdao.com/IUserService/UpdateCustomerResponse")]
        void UpdateCustomer(string email, zkdao.Web.UserServiceReference.UserData dataObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : zkdao.Web.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<zkdao.Web.UserServiceReference.IUserService>, zkdao.Web.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public zkdao.Web.UserServiceReference.UserData UserGetByID(System.Guid ID) {
            return base.Channel.UserGetByID(ID);
        }
        
        public zkdao.Web.UserServiceReference.UserData UserGetByEmail(string email) {
            return base.Channel.UserGetByEmail(email);
        }
        
        public zic_dotnet.Pager<zkdao.Web.UserServiceReference.UserData> UserGetPager(int pageNumber, int pageSize) {
            return base.Channel.UserGetPager(pageNumber, pageSize);
        }
        
        public System.Guid UserCreat(zkdao.Web.UserServiceReference.UserData dataObject) {
            return base.Channel.UserCreat(dataObject);
        }
        
        public bool UserValidate(string email, string password) {
            return base.Channel.UserValidate(email, password);
        }
        
        public void UpdateCustomer(string email, zkdao.Web.UserServiceReference.UserData dataObject) {
            base.Channel.UpdateCustomer(email, dataObject);
        }
    }
}
